config/routes.rb
Rails.application.routes.draw do
  get 'patient/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "facility#index"
  resources :facility, only: [:show, :index] do
    resources :patient, only: [:show] do
      member do
        get 'transfer'
      end
    end
  end
end

app/models/admission.rb
class Admission < ApplicationRecord
  belongs_to :patient, optional: false
  has_many :diagnoses
  has_many :symptoms
  has_many :observations

  def date
    moment.to_date.to_formatted_s(:long_ordinal)
  end

  def time
    moment.strftime('%l:%M %P')
  end
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :patient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  default_scope { self.acute } 

  belongs_to :patient, optional: true
  belongs_to :admission, optional: true
  validates :description, presence: true

  enum condition_type: [
    :chronic,
    :acute,
    :other
  ]

  def described_code
    "#{description} #{code}"
  end
end

app/models/diagnostic_procedure.rb
class DiagnosticProcedure < ApplicationRecord
  belongs_to :patient

  def time
    moment.strftime('%l:%M %P')
  end
end

app/models/facility.rb
class Facility < ApplicationRecord
    has_many :patients
end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord
  belongs_to :patient
  has_one :order_frequency
  
  enum unit: [
    :mg
  ]

  enum route: [
    :PO,
    :IM,
    :SC
  ]

  def frequency
    "#{order_frequency&.value}#{order_frequency&.unit}"
  end

  def dosage
    super.to_i.to_s + unit
  end
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :admission
end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord
  belongs_to :medication_order

  enum unit: [
    :hr
  ]
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :facility, optional: false
  
  has_many :admissions
  has_many :allergies
  has_many :diagnoses 
  has_many :diagnostic_procedures
  has_many :medications, class_name: 'MedicationOrder'
  has_many :treatments

  enum gender: [
    :male,
    :female,
    :other
  ] 
  
  def admission
    admissions.order(created_at: :desc).first
  end

  def age 
    ((Time.now - dob) / 60 / 60 / 24 / 365).floor
  end
  
  def formal_name
    "#{last_name}, #{first_name} #{middle_name}"
  end
  
  def full_name
  "#{first_name} #{middle_name} #{last_name}"
  end

  def chronic_conditions
    diagnoses.unscoped.chronic
  end
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  belongs_to :admission
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/facility_controller.rb
class FacilityController < ApplicationController
  def index
    @facilities = Facility.order(:name)
  end

  def show
    @facility = Facility.includes(:patients).find(params[:id])
  end
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
  def show
    @patient = Patient.find(params[:id])
  end

  def transfer
    @patient = Patient.includes(:facility, :admissions, :diagnoses).find(params[:id])
    @facility = @patient.facility
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facility_helper.rb
module FacilityHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/facility/index.html.erb
<div class="page-header">
  <h1>Facilities</h1>
</div>
<% @facilities.each do |facility| %>
  <h3><%= link_to facility.name, facility_path(facility) %></h3>
<% end %>

app/views/facility/show.html.erb
<div class="page-header">
  <h1><%= @facility.name %></h1>
  <h4>Current Patients</h4>
</div>

<table class="table table-striped">
  <tr>
  <th>MR No.</th>
  <th>Name</th>
  <th>DOB</th>
  <th>Admission Date</th>
  <th>Actions</th>
  </tr>
<% @facility.patients.each do |patient| %>
  <tr>
  <td><%= patient.mr %></td>
  <td><%= patient.formal_name %></td>
  <td><%= patient.dob.to_date %></td>
  <td><%= patient.admission.date%></td>
  <td><%= link_to "Transfer Form", transfer_facility_patient_path(@facility, patient)%></td>
  </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>St Bernard EMR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
  <nav class="navbar navbar-default navbar-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "St. Bernard EMR", root_path, class: 'navbar-brand'%>
        </div>
      </div>
    </nav>
  <div class = "container">
    <div class="row">
      <div class="col-xs-12">
          <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/patient/show.html.erb
<h1>Patient Transfer Order</h1>
<p><%= @patient.full_name %></p>

app/views/patient/transfer.html.erb
<div id="print-form" class="panel-group">
<div class="row">
  <div class="panel panel-info">
    <div class="panel-heading">
      <strong>Emergency Transfer Summary (Form 34L-D)</strong>
    </div>
  </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong>Transferring Facility</strong>
          </div>
          <div class="panel panel-body">
              <p class="text">Name</p>
              <p class="text text-primary"><%= @facility.name %></p>
          </div>
        </div>
      </div>
    </div>
</div>
<div class="row">
  <div class="panel panel-default border">
    <div class="panel-heading">
      <strong>Patient Information</strong>
    </div>
    <div class="row panel-body">
      <div class="col-xs-3 ">
        <div class=" border border-secondary panel-body">
          <p class="text ">First Name</p>
          <p class="text text-primary "><%= @patient.first_name %></p>
        </div>
      </div>
      <div class="col-xs-3">
        <div class=" border border-secondary panel-body">
          <p class="text ">Middle Name</p>
          <p class="text text-primary "><%= @patient.middle_name %></p>
        </div>
      </div>
      <div class="col-xs-3 ">
        <div class=" border border-secondary panel-body">
          <p class="text ">Last Name</p>
          <p class="text text-primary "><%= @patient.last_name %></p>
        </div>
      </div>
      <div class="col-xs-3 ">
          <div class=" border border-secondary panel-body">
            <p class="text ">Medical Record</p>
            <p class="text text-primary "><%= @patient.mr %></p>
          </div>
        </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>Summary</strong>
    </div>
    <div class="panel-body">
      <p>
        This <%=@patient.age%> years old <%=@patient.gender%> was admitted to <%=@patient.facility.name%> on <%=@patient.admission.date%> at <%=@patient.admission.time%> due to <%=@patient.admission.diagnoses.map{|d| d.described_code}.join(", ")%>. 
        The observed symptoms on admission were <%=@patient.admission.symptoms.pluck(:description).join(", ")%>.
        <%=@patient.admission.observations.pluck(:description).join(", ") %>.
      </p>
      <p>
        Upon asking about known allergies, the patient disclosed <%=@patient.allergies.pluck(:description).join(", ") %>. 
        Upon asking about chronic conditions, the patient disclosed <%=@patient.chronic_conditions.map{|cc| cc.described_code}.join(", ")%>. 
        The patient was administered with <%= @patient.medications.map{|med| "#{med.name} #{med.dosage} #{med.route} #{med.frequency} to #{med.necessity}"}.join(", ") %>.
      </p>
      <p>
        The staff performed <%=@patient.diagnostic_procedures.map{|dp| "#{dp.description} at #{dp.time}"}.join(", ") %>, revealing <%= @patient.diagnoses.map{|d| d.described_code}.join(", ") %>.
        Our team proceeded to <%=@patient.treatments.pluck(:description, :to, :necessity).map{|d| d.join(" ")}.join(", ")%>.
      </p>
    </div>
  </div>
</div>
</div>
<button class="btn btn-primary" onclick="printDiv('print-form')" value="print a div!">Print Form</button>